
spring:
  #db properties
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/food_test
    username: "postgres"
    password: "0322"

  #hibernate properties
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: false
        order_inserts: true
        jdbc:
          batch_size: 4
    open-in-view: false

  #security
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/spring-security-realm

  flyway:
    enabled: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  main:
    banner-mode: off

server:
  port: 8888

logging:
#  file: application.log
  level:
    com:
      boldyrev: debug
